# Document:
# http://simiki.org/docs/configuration.html

url: https://simonhe96.github.io/cgwiki/
title: CG-Wiki
keywords: simonhe,wiki,CG,pipline
description: Everything about CG
author: Simon_He

root: /cgwiki
source: content
destination: output
themes_dir: themes
theme: simple2

category:
  - name: linux
    label: Linux/运维
  - name: database
    label: 数据库

default_ext: md
pygments: true
debug: false

deploy:
  - type: git
    remote: origin
    branch: gh-pages
